basePath: /
definitions:
  models.Password:
    properties:
      id:
        type: string
      password:
        type: string
      site:
        type: string
    type: object
info:
  contact: {}
  description: This is an API for managing user passwords
  title: Password Management API
  version: "1.0"
paths:
  /password:
    get:
      consumes:
      - application/json
      description: Get passwords by site name for the user
      parameters:
      - description: Site name
        in: query
        name: site
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of passwords
          schema:
            items:
              $ref: '#/definitions/models.Password'
            type: array
        "400":
          description: Site name is required
          schema:
            type: string
        "500":
          description: Failed to fetch passwords
          schema:
            type: string
      summary: Get Passwords By Site
      tags:
      - Password
    post:
      consumes:
      - application/json
      description: Create a new password for the user
      parameters:
      - description: Password
        in: body
        name: Password
        required: true
        schema:
          $ref: '#/definitions/models.Password'
      produces:
      - application/json
      responses:
        "201":
          description: Password created successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Failed to create password
          schema:
            type: string
      summary: Create Password
      tags:
      - Password
  /password/:userID:
    get:
      consumes:
      - application/json
      description: Get all passwords for a user by user ID
      produces:
      - application/json
      responses:
        "200":
          description: List of passwords
          schema:
            items:
              $ref: '#/definitions/models.Password'
            type: array
        "500":
          description: Failed to fetch passwords
          schema:
            type: string
      summary: Get All Passwords
      tags:
      - Password
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
